baseURL = "https://www.johnyn.com/"
languageCode = "zh-cn"
title = "后会有期"
theme="hugo-theme-ling"
paginate = 10
paginatePath = "page"
hasCJKLanguage="true"
titleCaseStyle = "Go"
[permalinks]
  post = "/:year/:month/:day/:title/"
[params]
  themeColor = "theme-cyan"
  keywords = "Web开发技术，web开发，数据库相关，PHP相关，golang相关，docker相关，git相关"
  description = "基于Hugo,专注Web开发技术分享,包括数据可视化，前端、数据库、PHP、golang、Elasticsearch等"
  subTitle = "青山不改，绿水长流 carpe diem"
  qrcode = "/img/qrcode.jpg"
  ICP = '粤ICP备2021017283号-1'
[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/jangworn/"}
  ]
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "manni"
    tabWidth = 4
[outputs]
  home = ["HTML", "RSS", "JSON"]
